export const errorMessages = {
    token_expired: 'Tarattığınız QR kodu geçersiz veya kullanım süresi dolmuştur. Lütfen tekrar deneyin.',
    entrance_error: 'Aynı gün içerisinde çıkış yapmadan aynı QR kodu ile birden fazla giriş yapamazsınız.',
    exit_error: 'Aynı gün içerisinde giriş yapmadan aynı QR kodu ile birden fazla çıkış yapamazsınız.',
    email_already_exists: 'Bu e-posta adresi veya kullanıcı adı ile daha önce kayıt oluşturulmuş.',
    invalid_email_or_password: 'E-posta adresi, Kullanıcı adı veya şifre hatalı.',
    user_already_active: 'Kullanıcı zaten aktif durumda.',
    user_alreacy_inactive: 'Kullanıcı zaten arşivlenmiş durumda.',
    no_selected_user_found: 'Kullanıcı bulunamadı.',
    'file-invalid-type': 'Dosya türü image/jpeg, image/png olmalıdır.',
    'too-many-files': 'Tek seferde yalnızca bir görsel seçebilirsiniz.',
    invalid_client_or_secret_key: 'Geçersiz istemci veya gizli anahtar.',
    user_is_not_active: 'Kullanıcı aktif değil.',
    spending_is_pending: 'Onaylanmamış harcamalarınız bulunmaktadır. Onaylatmak için birim yöneticiniz ile iletişime geçiniz.',
    key_is_missing: 'API anahtarı eksik veya hatalı.',
    secret_is_missing: 'API gizli anahtarı eksik veya hatalı.',
    email_is_missing: 'E-posta adresi eksik veya hatalı.',
    password_is_missing: 'Şifre eksik veya hatalı.',
    refreshtoken_is_missing: 'Yenileme anahtarı eksik veya hatalı.',
    verifypassword_is_missing: 'Şifre doğrulama eksik veya hatalı.',
    token_is_missing: 'Token eksik veya hatalı.',
    unauthorized: 'Yetkisiz işlem.',
    extra_pay_approved_before: 'Ek ödeme daha önce onaylanmış.',
    payment_not_found: 'Avans bulunamadı.',
    notification_not_created: 'Bildirim oluşturulamadı.',
    extrapay_not_found: 'Ek ödeme bulunamadı.',
    no_notification_found: 'Bildirim bulunamadı.',
    extrapay_not_created: 'Ek ödeme oluşturulamadı.',
    refund_not_created: 'İade oluşturulamadı.',
    payment_has_been_completed_before: 'Avans daha önce kapatılmış.',
    payment_status_should_be_approved: 'Avans onaylanmış olmalıdır.',
    payment_could_not_be_created: 'Avans oluşturulamadı.',
    no_selected_payment_found: 'Avans bulunamadı.',
    payment_already_rejected: 'Avans daha önce reddedilmiş.',
    payment_could_not_be_updated: 'Avans güncellenemedi.',
    payment_could_not_be_approved: 'Avans onaylanamadı.',
    'Internal Server Error': 'Sunucu tarafında beklenmeyen bir hata oluştu.',
};
